name: Daily

on:
  schedule:
    # At minute 0 past every hour from 9 through 17 on every day-of-week from Sunday through Thursday.
    # 6-14 -> 9-17
    - cron: '0 6-14 * * SUN-THU'

jobs:
  build:
    name: Build
    runs-on: "ubuntu-18.04"
    steps:
      - name: Run
        run: docker run -e WORK_EMAIL=${{ secrets.WORK_EMAIL }} -e PERSONAL_EMAIL=${{ secrets.PERSONAL_EMAIL }} -e GOOGLE_SA_BASE64=${{ secrets.GOOGLE_SA_BASE64 }} -e TRELLO_APP_ID=${{ secrets.TRELLO_APP_ID }} -e TRELLO_TOKEN=${{ secrets.TRELLO_TOKEN }} -e TRELLO_BOARD=${{ secrets.TRELLO_BOARD }} -e AIRTABLE_API_KEY=${{ secrets.AIRTABLE_API_KEY }} -e AIRTABLE_DATABASE_ID=${{ secrets.AIRTABLE_DATABASE_ID }} -e AIRTABLE_TABLE_NAME=${{ secrets.AIRTABLE_TABLE_NAME }} olsynt/syncer
