name: Daily

on:
  push:
    branches: [ master ]
  schedule:
    # At minute 0 past every hour from 9 through 17 on every day-of-week from Sunday through Thursday.
    - cron: '0 9-17 * * SUN-THU'

jobs:
  build:
    name: Build
    runs-on: "ubuntu-18.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: docker build -t syncer .
      
      - name: Run
        run: docker run -e GOOGLE_SA_BASE64=${{ secrets.GOOGLE_SA_BASE64 }} -e TRELLO_APP_ID=${{ secrets.TRELLO_APP_ID }} -e TRELLO_TOKEN=${{ secrets.TRELLO_TOKEN }} -e TRELLO_BOARD=${{ secrets.TRELLO_BOARD }} -e AIRTABLE_API_KEY=${{ secrets.AIRTABLE_API_KEY }} -e AIRTABLE_DATABASE_ID=${{ secrets.AIRTABLE_DATABASE_ID }} -e AIRTABLE_TABLE_NAME=${{ secrets.AIRTABLE_TABLE_NAME }} syncer
